services:
  levilamina-server:
    image: ghcr.io/liteldev/levilamina-server:latest-wine
    environment:
      LC_ALL: ru_RU.UTF-8
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
    ports:
      - 19132:19132/udp
    volumes:
      - levilamina-server-data:/data
    stdin_open: true
    tty: true

volumes:
  levilamina-server-data:
